<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="TAP and CSV Output Example" tests="6" failures="1" errors="1" skipped="1" time="0.05">
  <testsuite name="TAP and CSV Output Example" tests="6" failures="1" errors="1" skipped="1" time="0.05" timestamp="2025-03-09T01:41:12">
    <properties>
      <property name="lust_next_version" value="0.7.5"/>
    </properties>
    <testcase name="can add numbers" classname="Math operations" time="0.001"/>
    <testcase name="can subtract numbers" classname="Math operations" time="0.001"/>
    <testcase name="can concatenate strings" classname="String operations" time="0.001"/>
    <testcase name="fails when comparing case-sensitive strings" classname="String operations" time="0.002">
      <failure message="Values are not equal" type="AssertionError">Expected: &apos;hello&apos;
Received: &apos;HELLO&apos;</failure>
    </testcase>
    <testcase name="has a pending test" classname="Advanced features" time="0.0">
      <skipped/>
    </testcase>
    <testcase name="causes an error" classname="Advanced features" time="0.001">
      <error message="Runtime error in test" type="Error">This is a simulated error
stack traceback:
	[C]: in function &apos;error&apos;
	examples/tap_csv_report_example.lua:47: in function &lt;examples/tap_csv_report_example.lua:46&gt;</error>
    </testcase>
  </testsuite>
</testsuites>